# The base image is only used for build-dev (see last step)
# Here we install all development tools that might be handy during debug
FROM python:3.8.1-buster AS base
RUN apt-get update && \
    apt-get install -y --no-install-recommends vim netcat && \
    rm -rf /var/lib/apt/lists/*

# The builder image contains all required python modules
FROM python:3.8.1-buster AS builder
COPY requirements.txt /requirements.txt
RUN apt-get update && apt-get install -y --no-install-recommends --yes python3-venv gcc libpython3-dev && \
    python3 -m venv /venv && \
    /venv/bin/pip install --upgrade pip && \
    /venv/bin/pip install -r /requirements.txt && \
    /venv/bin/pip install ipdb  # Extra development tools not available in prod image

# From our base image, copy the artifacts from previous stages (virtual env and app)
FROM base AS runner
COPY --from=builder /venv /venv
COPY . /app
#ENVIRONMENT_VARS
#EXPOSED_PORTS
ENV PATH=/venv/bin/:${PATH}
WORKDIR /app
ENTRYPOINT ["/venv/bin/python3", "-m", "demo"]
# Run as root for development
USER 0
LABEL name={NAME}
LABEL version={VERSION}

