name: Push Docker container

on:
  push:
    tags:
      - '*'

jobs:
  push:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v1
      
      - name: Log into Registry
        run: echo "${{ secrets.REGISTRY_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin
      
      - name: Push to GitHub Package Registry
        run: ./build.sh --project prod --version $(echo ${GITHUB_REF:10}) --upload

